// Types example
// STEP ONE
export const GET_USERS = "GET_USERS";
export const SEND_MESSAGES = "SEND_MESSAGES";
export const GET_CHANNEL_DETAILS = "GET_CHANNEL_DETAILS";
export const GET_PINNED_MESSAGES = "GET_PINNED_MESSAGES";
export const PIN_MESSAGE = "PIN_MESSAGE";
export const ARCHIVE_CHANNEL = "ARCHIVE_CHANNEL";
export const GET_CHANNELS = "GET_CHANNELS";
