// Types example
// STEP ONE
export const GET_USERS = "GET_USERS";
export const GET_CHANNELMESSAGES = "GET_CHANNELMESSAGES";
export const ADD_CHANNELMESSAGES = "ADD_CHANNELMESSAGES";
export const UPDATE_CHANNELMESSAGES = "UPDATE_CHANNELMESSAGES";
export const DELETE_CHANNELMESSAGES = "DELETE_CHANNELMESSAGES";
export const GET_CHANNEL_DETAILS = "GET_CHANNEL_DETAILS";
export const GET_CHANNEL_THREAD_MESSAGES = "GET_CHANNEL_DETAILS";
export const SEND_MESSAGES = "SEND_MESSAGES";
export const GET_PINNED_MESSAGES = "GET_PINNED_MESSAGES";
export const PIN_MESSAGE = "PIN_MESSAGE";
export const ARCHIVE_CHANNEL = "ARCHIVE_CHANNEL";
export const GET_CHANNELS = "GET_CHANNELS";
export const CREATE_CHANNELS = "CREATE_CHANNELS";
export const GET_SOCKETS = "GET_SOCKETS";
export const GET_RENDEREDMESSAGES = "GET_RENDEREDMESSAGES";
export const ADD_CHANNEL_MEMBER = "ADD_CHANNEL_MEMBER";
export const REMOVE_CHANNEL_MEMBER = "ADD_CHANNEL_MEMBER";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const USER_CAN_INPUT = "USER_CAN_INPUT";
export const GET_FILES = 'GET_FILES';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const GET_WORKSPACE_USERS = "GET_WORKSPACE_USERS";
export const GET_NOTIFICATION_SETTINGS = "GET_NOTIFICATION_SETTINGS";
