name: Channels Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Exec remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zc_plugin_channels/
            git checkout dev
            git pull origin dev
            cd frontend
            yarn install
            yarn relocate
            cd /var/www/zc_plugin_channels/backend/channel_plugin/
            source .venv/bin/activate
            python3 manage.py collectstatic --noinput
            fuser -k -HUP 3001/tcp
